### ISSUE TITLE
running the simulator 

### ISSUE THREAD

**Issue by Ulterior** [jamieiles/80x86#7]
Hi Jamie, its a little unclear how to run the simulator after ./scripts/build

I get the following error when running ./_build/build/sim/simulator

./_build/build/sim/simulator: error while loading shared libraries: libsimdisplay.so: cannot open shared object file: No such file or directory

Is this related to running cmake? Could you please provide some command line examples to get it running?

**Comment by jamieiles** [comment]
The project is built in the docker container and so needs to be run in that container too:

`./docker/s80x86-build -c "./_build/build/sim/simulator"`

**Comment by Ulterior** [comment]
Hi Jamie, still cant get over noob stuff with simulator :)

I downloaded your freedos.img and used it with the built bios in _build/build/sim/bios-sim and the result after launch is it locks up and does nothing after reading it. I tried dozen of freedos images from internet and the result is same. I turned on trace option and it goes into a loop with all 00 00 00 after reading sd cad image.

![image](https://user-images.githubusercontent.com/905303/52847593-4a2c4400-3115-11e9-90bf-087116971c3b.png)

I just wanted to run simulator and see it boot freedos, maybe I am still not issuing all the necessary commands?

**Comment by jamieiles** [comment]
I have updated the disk image (https://www.jamieiles.com/80186/freedos-20190220.img.xz) which has the right disk geometry for the latest bios, please unxz that and give it a go.

**Comment by Ulterior** [comment]
works great now, thanks for taking care of that, Jamie

**Comment by listenchin** [comment]
The 

> I have updated the disk image (https://www.jamieiles.com/80186/freedos-20190220.img.xz) which has the right disk geometry for the latest bios, please unxz that and give it a go.

The link to the disk image appears to have expired. The disk image I downloaded from the project homepage is experiencing the same issue in the simulator as reported by this user. How can I resolve this?Thank you very much.
